name: shopPlugin
version: '1.0-SNAPSHOT'
main: com.hanabi.shopplugin.ShopPlugin
api-version: '1.20'

commands:
  createsign:
    description: 看板を作成する
    permission: createsign.command
permissions:
  createsign.command:
    default: op